export default [
  "links.link_1",
  "links.link_2",
  "links.link_3",
  "links.link_4",
  "links.link_5",
  "links.link_6",
  "links.link_7",
  "links.link_8",
  "links.link_9",
  "links.link_10",
  "links.link_11",
  "links.link_12",
  "links.link_13",
  "links.link_14",
  "links.link_15",
];
